### ISSUE TITLE
 OSError: image file is truncated (5 bytes not processed)

### ISSUE THREAD

**Issue by sinsforeal** [p1atdev/stable-diffusion-webui-cafe-aesthetic#1]
I ran into this problem with images that are truncated when attempting to process several very large datasets. The solution I discovered was to add "from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True" under "from PIL import Image" in aesthetic.py. I don't know how to do a pull request but anyway if anyone else has this problem here you go!

**Comment by p1atdev** [comment]
Thank you for reporting this issue! I am closing this issue as I believe it is fixed, but please let me know if you encounter any further issues.
