### ISSUE TITLE
Not_aesthetic content missing

### ISSUE THREAD

**Issue by mykeehu** [p1atdev/stable-diffusion-webui-cafe-aesthetic#4]
I wanted batch-based sorting, and it created the not_aesthetic folder, but it didn't copy any content into it, it was left empty.
Is this a bug?

**Comment by p1atdev** [comment]
Perhaps you are using absolute thresholds to classify? If the threshold is 0.9, then it is only classified as not_aesthetic if the likelihood of not_aesthetic is greater than 90%, and if aesthetic is less than 90% and not_aesthetic is also less than 90%, then the copy or move will not be performed.

**Comment by mykeehu** [comment]
Yes, I used an absolute value with a setting of 0.9. I just wanted to know which images were not included in the aesthetic category.

**Comment by p1atdev** [comment]
The image will go into the aesthetics folder if it is 90% aesthetics and into the not_aesthetic folder if it is 90% not_aesthetic. If neither probability is low (e.g. 60%:40%), it will go in neither.
